### ISSUE TITLE
pipx reinstall-all kills itself

### ISSUE THREAD

**Issue by rpdelaney** [mattsb42/pipx-in-pipx#25]
Since pipx is managed by pipx, `reinstall-all` causes pipx to uninstall itself. It cannot reinstall itself since it no longer exists.

I understand from the docs that it seems `reinstall-all` is no longer necessary when upgrading the python interpreter, but it's still a bit of a pit trap.

```console
$ pipx reinstall-all
[..snip..]
uninstalled pipx! ✨ 🌟 ✨

Traceback (most recent call last):
  File "/home/ryan/.local/bin/pipx", line 8, in <module>
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/main.py", line 591, in cli
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/main.py", line 194, in run_pipx_command
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/reinstall.py", line 75, in reinstall_all
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/reinstall.py", line 25, in reinstall
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/commands/install.py", line 53, in install
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/venv.py", line 126, in create_venv
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/util.py", line 129, in run
  File "/home/ryan/.local/pipx/venvs/pipx/lib/python3.8/site-packages/pipx/util.py", line 116, in run_subprocess
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ryan/.local/pipx/venvs/pipx/bin/python'
```

**Comment by mattsb42** [comment]
Hmm, good catch.

I'm inclined to say that this is "as designed" because of the reasons that I talk about in the readme wrt uninstalling[1]. I think this is just another manifestation of that. It would be good to expand the docs to call this out, though.

[1] https://github.com/mattsb42/pipx-in-pipx#uninstalling
